### ISSUE TITLE
http-proxy-middleware

### ISSUE THREAD

**Issue by xavivzla** [ghondar/crassa#17]
the library update, you have to make the change in the proxy

**OLD**
`const proxy = require('http-proxy-middleware')`

**NEW**
`const { createProxyMiddleware } = require('http-proxy-middleware')`

**Example**

```
const { createProxyMiddleware } = require('http-proxy-middleware')

module.exports = function(app) {
  const port = process.env.REACT_APP_PORT_SERVER || 5000
  app.use(createProxyMiddleware('/api', { target: `http://localhost:${port}/` }))
}

```

**Comment by ghondar** [comment]
sure, here is my [change](https://github.com/ghondar/counter-with-redux-ducks-and-sagas-template/commit/3bbb2c58ac630df6f491b8a3c00eb4f2d0ed793d)
